name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boringtun:$(date +%s)
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/uinta-labs/boringtun/boringtun:$(date +%s)
        username: uinta-labs
        password: ${{ secrets.PACKAGE_REGISTRY_PASSWORD }}
        registry: docker.pkg.github.com
